Fix incorrectly referenced library path

diff --git a/bin/njs b/bin/njs
--- a/bin/njs
+++ b/bin/njs
@@ -2,18 +2,19 @@
 
 function STDERR { cat - 1>&2; }
 
-if [ -e /usr/bin/node ]; then
-	NODE=/usr/bin/node;
-else
-	NODE=$(which node);
-fi
 
-
-
+NODE=$(which node);
 if [ "$NODE" == "" ]; then
 	echo "node cannot be found!" | STDERR;
 	exit 1;
 fi
 
-LIB_DIR=$(dirname $(dirname $(/usr/bin/rpath $0)))/lib
+RPATH=$(which rpath);
+if [ "$RPATH" == "" ]; then
+	echo "rpath cannot be found!" | STDERR;
+	exit 1;
+fi
+
+
+LIB_DIR=$(dirname $(dirname $($RPATH $0)))/lib
 $NODE --experimental-worker --experimental-modules --loader "${LIB_DIR}/esm-js.loader.mjs" "$@"
